[tools]
python = "3.12"

[env]
_.python.venv = { path = ".venv", create = true, uv_create_args = ["--seed"] }

[tasks.install]
description = "Install dependencies"
run = "pip install -e ."

[tasks.run]
description = "Run the FastAPI app"
depends = ["install"]
run = "uvicorn app.main:app --reload"
